### ISSUE TITLE
无法取到表，报错

### ISSUE THREAD

**Issue by aliubisi** [ieiayaobb/dynamoc_web#3]
vue.esm.js?65d7:610 [Vue warn]: Computed property "connectShow" was assigned to but it has no setter.

found in

---> <Connect> at E:\workspace\dynamoc_web-master\src\components\Connect.vue
       <Framework> at E:\workspace\dynamoc_web-master\src\components\Framework.vue
         <Root>

POST http://10.0.17.70:8000/ 400 (Bad Request)
:8080/#/:1 Access to XMLHttpRequest at 'http://10.0.17.70:8000/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2xhr.js?28e2:81 POST http://10.0.17.70:8000/ 400 (Bad Request)
handleRequest @ xhr.js?28e2:81
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
setTimeout (async)
RESET_RETRY_STATE @ event_listeners.js?00de:470
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:326
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
error @ event_listeners.js?00de:325
(anonymous) @ xhr.js?28e2:52
error (async)
handleRequest @ xhr.js?28e2:51
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:149
(anonymous) @ util.js?bbc0:725
hash @ util.js?bbc0:457
sha256 @ util.js?bbc0:408
computeSha256 @ util.js?bbc0:723
COMPUTE_SHA256 @ event_listeners.js?00de:143
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:86
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
VALIDATE_CREDENTIALS @ event_listeners.js?00de:81
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
runTo @ request.js?1405:403
send @ request.js?1405:367
makeRequest @ service.js?9975:205
svc.(anonymous function) @ service.js?9975:653
(anonymous) @ index.js?2848:19
F @ _export.js?ece2:36
scan @ index.js?2848:18
setResults @ actions.js?a7ea:48
wrappedActionHandler @ vuex.esm.js?edaa:704
dispatch @ vuex.esm.js?edaa:426
boundDispatch @ vuex.esm.js?edaa:332
queryWithKey @ actions.js?a7ea:66
wrappedActionHandler @ vuex.esm.js?edaa:704
dispatch @ vuex.esm.js?edaa:426
boundDispatch @ vuex.esm.js?edaa:332
query @ QueryCondition.vue?38a8:94
invoker @ vue.esm.js?65d7:2128
Vue.$emit @ vue.esm.js?65d7:2648
handleClick @ element-ui.common.js?a187:7211
invoker @ vue.esm.js?65d7:2128
fn._withTask.fn._withTask @ vue.esm.js?65d7:1913
:8080/#/:1 Access to XMLHttpRequest at 'http://10.0.17.70:8000/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2xhr.js?28e2:81 POST http://10.0.17.70:8000/ 400 (Bad Request)
handleRequest @ xhr.js?28e2:81
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
setTimeout (async)
RESET_RETRY_STATE @ event_listeners.js?00de:470
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:326
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
error @ event_listeners.js?00de:325
(anonymous) @ xhr.js?28e2:52
error (async)
handleRequest @ xhr.js?28e2:51
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
setTimeout (async)
RESET_RETRY_STATE @ event_listeners.js?00de:470
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:326
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
error @ event_listeners.js?00de:325
(anonymous) @ xhr.js?28e2:52
error (async)
handleRequest @ xhr.js?28e2:51
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:149
(anonymous) @ util.js?bbc0:725
hash @ util.js?bbc0:457
sha256 @ util.js?bbc0:408
computeSha256 @ util.js?bbc0:723
COMPUTE_SHA256 @ event_listeners.js?00de:143
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:86
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
VALIDATE_CREDENTIALS @ event_listeners.js?00de:81
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
runTo @ request.js?1405:403
send @ request.js?1405:367
makeRequest @ service.js?9975:205
svc.(anonymous function) @ service.js?9975:653
(anonymous) @ index.js?2848:19
F @ _export.js?ece2:36
scan @ index.js?2848:18
setResults @ actions.js?a7ea:48
wrappedActionHandler @ vuex.esm.js?edaa:704
dispatch @ vuex.esm.js?edaa:426
boundDispatch @ vuex.esm.js?edaa:332
queryWithKey @ actions.js?a7ea:66
wrappedActionHandler @ vuex.esm.js?edaa:704
dispatch @ vuex.esm.js?edaa:426
boundDispatch @ vuex.esm.js?edaa:332
query @ QueryCondition.vue?38a8:94
invoker @ vue.esm.js?65d7:2128
Vue.$emit @ vue.esm.js?65d7:2648
handleClick @ element-ui.common.js?a187:7211
invoker @ vue.esm.js?65d7:2128
fn._withTask.fn._withTask @ vue.esm.js?65d7:1913
:8080/#/:1 Access to XMLHttpRequest at 'http://10.0.17.70:8000/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2xhr.js?28e2:81 POST http://10.0.17.70:8000/ 400 (Bad Request)
handleRequest @ xhr.js?28e2:81
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
setTimeout (async)
RESET_RETRY_STATE @ event_listeners.js?00de:470
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:326
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
error @ event_listeners.js?00de:325
(anonymous) @ xhr.js?28e2:52
error (async)
handleRequest @ xhr.js?28e2:51
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
setTimeout (async)
RESET_RETRY_STATE @ event_listeners.js?00de:470
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:326
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
error @ event_listeners.js?00de:325
(anonymous) @ xhr.js?28e2:52
error (async)
handleRequest @ xhr.js?28e2:51
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
setTimeout (async)
RESET_RETRY_STATE @ event_listeners.js?00de:470
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:326
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
error @ event_listeners.js?00de:325
(anonymous) @ xhr.js?28e2:52
error (async)
handleRequest @ xhr.js?28e2:51
executeSend @ event_listeners.js?00de:334
SEND @ event_listeners.js?00de:348
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:233
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
SIGN @ event_listeners.js?00de:204
callListeners @ sequential_executor.js?c786:102
callNextListener @ sequential_executor.js?c786:96
discoverEndpoint @ discover_endpoint.js?41bb:323
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:149
(anonymous) @ util.js?bbc0:725
hash @ util.js?bbc0:457
sha256 @ util.js?bbc0:408
computeSha256 @ util.js?bbc0:723
COMPUTE_SHA256 @ event_listeners.js?00de:143
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
(anonymous) @ state_machine.js?1f54:26
(anonymous) @ request.js?1405:38
(anonymous) @ request.js?1405:685
callListeners @ sequential_executor.js?c786:116
callNextListener @ sequential_executor.js?c786:96
(anonymous) @ event_listeners.js?00de:86
finish @ config.js?2ac6:348
(anonymous) @ config.js?2ac6:366
get @ credentials.js?179e:127
getAsyncCredentials @ config.js?2ac6:360
getCredentials @ config.js?2ac6:380
VALIDATE_CREDENTIALS @ event_listeners.js?00de:81
callListeners @ sequential_executor.js?c786:102
emit @ sequential_executor.js?c786:78
emit @ request.js?1405:683
transition @ request.js?1405:22
runTo @ state_machine.js?1f54:14
runTo @ request.js?1405:403
send @ request.js?1405:367
makeRequest @ service.js?9975:205
svc.(anonymous function) @ service.js?9975:653
(anonymous) @ index.js?2848:19
F @ _export.js?ece2:36
scan @ index.js?2848:18
setResults @ actions.js?a7ea:48
wrappedActionHandler @ vuex.esm.js?edaa:704
dispatch @ vuex.esm.js?edaa:426
boundDispatch @ vuex.esm.js?edaa:332
queryWithKey @ actions.js?a7ea:66
wrappedActionHandler @ vuex.esm.js?edaa:704
dispatch @ vuex.esm.js?edaa:426
boundDispatch @ vuex.esm.js?edaa:332
query @ QueryCondition.vue?38a8:94
invoker @ vue.esm.js?65d7:2128
Vue.$emit @ vue.esm.js?65d7:2648
handleClick @ element-ui.common.js?a187:7211
invoker @ vue.esm.js?65d7:2128
fn._withTask.fn._withTask @ vue.esm.js?65d7:1913
:8080/#/:1 Access to XMLHttpRequest at 'http://10.0.17.70:8000/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ieiayaobb** [comment]
Access to XMLHttpRequest at 'http://10.0.17.70:8000/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource
跨域了，服务端需要支持跨域请求

**Comment by aliubisi** [comment]
> Access to XMLHttpRequest at 'http://10.0.17.70:8000/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource
> 跨域了，服务端需要支持跨域请求

已经解决，非常感谢
